apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yco99h3ms-nodejs
  janus-idp.io/tekton: yco99h3ms-nodejs
  backstage.io/kubernetes-id: yco99h3ms-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yco99h3ms-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
